return {
    schema = 1,
    managerVersion = "1.0.0",
    managerFiles = {
        "config/repository.lua",
        "config/settings.lua",
        "core/backup.lua",
        "core/checksum.lua",
        "core/filesystem.lua",
        "core/installed.lua",
        "core/installer.lua",
        "core/logger.lua",
        "core/packages.lua",
        "core/remote.lua",
        "core/repair.lua",
        "core/uninstaller.lua",
        "core/updater.lua",
        "core/verifier.lua",
        "core/version.lua",
        "ui/menu.lua",
        "ui/progress.lua",
        "ui/theme.lua",
        "manager.lua",
        "update-manager.lua",
        "startup",
    },
    packages = {
        {
            folder = "server",
            version = "0.8.3",
            files = {
                "changelog.lua",
                "files/banqueos/config.lua",
                "files/banqueos/core/database.lua",
                "files/banqueos/core/money.lua",
                "files/banqueos/core/network.lua",
                "files/banqueos/core/storage.lua",
                "files/banqueos/core/ui.lua",
                "files/banqueos/main.lua",
                "files/banqueos/screens/accounts.lua",
                "files/banqueos/screens/atms.lua",
                "files/banqueos/screens/cards.lua",
                "files/banqueos/screens/create_account.lua",
                "files/banqueos/screens/create_card.lua",
                "files/banqueos/screens/loading.lua",
                "files/banqueos/screens/menu.lua",
                "files/banqueos/screens/placeholder.lua",
                "files/startup",
                "package.lua",
            },
        },
        {
            folder = "atm",
            version = "0.2.3",
            files = {
                "changelog.lua",
                "files/banqueos_atm/config.lua",
                "files/banqueos_atm/main.lua",
                "files/startup",
                "package.lua",
            },
        },
    }
}
